//
//  CountryListVM.swift
//  Tidoy
//
//  Created by Codes Orbit on 20/08/2024.
//

import Foundation
class CountryListVM: ObservableObject {
    let countryDictionary: [String: (code: String, flag: String)] = [
        "Afghanistan": (code: "+93", flag: "🇦🇫"),
        "Albania": (code: "+355", flag: "🇦🇱"),
        "Algeria": (code: "+213", flag: "🇩🇿"),
        "American Samoa": (code: "+1-684", flag: "🇦🇸"),
        "Andorra": (code: "+376", flag: "🇦🇩"),
        "Angola": (code: "+244", flag: "🇦🇴"),
        "Anguilla": (code: "+1-264", flag: "🇦🇮"),
        "Antarctica": (code: "+672", flag: "🇦🇶"),
        "Antigua and Barbuda": (code: "+1-268", flag: "🇦🇬"),
        "Argentina": (code: "+54", flag: "🇦🇷"),
        "Armenia": (code: "+374", flag: "🇦🇲"),
        "Aruba": (code: "+297", flag: "🇦🇼"),
        "Australia": (code: "+61", flag: "🇦🇺"),
        "Austria": (code: "+43", flag: "🇦🇹"),
        "Azerbaijan": (code: "+994", flag: "🇦🇿"),
        "Bahamas": (code: "+1-242", flag: "🇧🇸"),
        "Bahrain": (code: "+973", flag: "🇧🇭"),
        "Bangladesh": (code: "+880", flag: "🇧🇩"),
        "Barbados": (code: "+1-246", flag: "🇧🇧"),
        "Belarus": (code: "+375", flag: "🇧🇾"),
        "Belgium": (code: "+32", flag: "🇧🇪"),
        "Belize": (code: "+501", flag: "🇧🇿"),
        "Benin": (code: "+229", flag: "🇧🇯"),
        "Bermuda": (code: "+1-441", flag: "🇧🇲"),
        "Bhutan": (code: "+975", flag: "🇧🇹"),
        "Bolivia": (code: "+591", flag: "🇧🇴"),
        "Bosnia and Herzegovina": (code: "+387", flag: "🇧🇦"),
        "Botswana": (code: "+267", flag: "🇧🇼"),
        "Brazil": (code: "+55", flag: "🇧🇷"),
        "British Indian Ocean Territory": (code: "+246", flag: "🇮🇴"),
        "British Virgin Islands": (code: "+1-284", flag: "🇻🇬"),
        "Brunei": (code: "+673", flag: "🇧🇳"),
        "Bulgaria": (code: "+359", flag: "🇧🇬"),
        "Burkina Faso": (code: "+226", flag: "🇧🇫"),
        "Burundi": (code: "+257", flag: "🇧🇮"),
        "Cambodia": (code: "+855", flag: "🇰🇭"),
        "Cameroon": (code: "+237", flag: "🇨🇲"),
        "Canada": (code: "+1", flag: "🇨🇦"),
        "Cape Verde": (code: "+238", flag: "🇨🇻"),
        "Cayman Islands": (code: "+1-345", flag: "🇰🇾"),
        "Central African Republic": (code: "+236", flag: "🇨🇫"),
        "Chad": (code: "+235", flag: "🇹🇩"),
        "Chile": (code: "+56", flag: "🇨🇱"),
        "China": (code: "+86", flag: "🇨🇳"),
        "Christmas Island": (code: "+61", flag: "🇨🇽"),
        "Cocos Islands": (code: "+61", flag: "🇨🇨"),
        "Colombia": (code: "+57", flag: "🇨🇴"),
        "Comoros": (code: "+269", flag: "🇰🇲"),
        "Cook Islands": (code: "+682", flag: "🇨🇰"),
        "Costa Rica": (code: "+506", flag: "🇨🇷"),
        "Croatia": (code: "+385", flag: "🇭🇷"),
        "Cuba": (code: "+53", flag: "🇨🇺"),
        "Curaçao": (code: "+599", flag: "🇨🇼"),
        "Cyprus": (code: "+357", flag: "🇨🇾"),
        "Czech Republic": (code: "+420", flag: "🇨🇿"),
        "Democratic Republic of the Congo": (code: "+243", flag: "🇨🇩"),
        "Denmark": (code: "+45", flag: "🇩🇰"),
        "Djibouti": (code: "+253", flag: "🇩🇯"),
        "Dominica": (code: "+1-767", flag: "🇩🇲"),
        "Dominican Republic": (code: "+1-809", flag: "🇩🇴"),
        "Ecuador": (code: "+593", flag: "🇪🇨"),
        "Egypt": (code: "+20", flag: "🇪🇬"),
        "El Salvador": (code: "+503", flag: "🇸🇻"),
        "Equatorial Guinea": (code: "+240", flag: "🇬🇶"),
        "Eritrea": (code: "+291", flag: "🇪🇷"),
        "Estonia": (code: "+372", flag: "🇪🇪"),
        "Eswatini": (code: "+268", flag: "🇸🇿"),
        "Ethiopia": (code: "+251", flag: "🇪🇹"),
        "Falkland Islands": (code: "+500", flag: "🇫🇰"),
        "Faroe Islands": (code: "+298", flag: "🇫🇴"),
        "Fiji": (code: "+679", flag: "🇫🇯"),
        "Finland": (code: "+358", flag: "🇫🇮"),
        "France": (code: "+33", flag: "🇫🇷"),
        "French Polynesia": (code: "+689", flag: "🇵🇫"),
        "Gabon": (code: "+241", flag: "🇬🇦"),
        "Gambia": (code: "+220", flag: "🇬🇲"),
        "Georgia": (code: "+995", flag: "🇬🇪"),
        "Germany": (code: "+49", flag: "🇩🇪"),
        "Ghana": (code: "+233", flag: "🇬🇭"),
        "Gibraltar": (code: "+350", flag: "🇬🇮"),
        "Greece": (code: "+30", flag: "🇬🇷"),
        "Greenland": (code: "+299", flag: "🇬🇱"),
        "Grenada": (code: "+1-473", flag: "🇬🇩"),
        "Guam": (code: "+1-671", flag: "🇬🇺"),
        "Guatemala": (code: "+502", flag: "🇬🇹"),
        "Guinea": (code: "+224", flag: "🇬🇳"),
        "Guinea-Bissau": (code: "+245", flag: "🇬🇼"),
        "Guyana": (code: "+592", flag: "🇬🇾"),
        "Haiti": (code: "+509", flag: "🇭🇹"),
        "Honduras": (code: "+504", flag: "🇭🇳"),
        "Hong Kong": (code: "+852", flag: "🇭🇰"),
        "Hungary": (code: "+36", flag: "🇭🇺"),
        "Iceland": (code: "+354", flag: "🇮🇸"),
        "India": (code: "+91", flag: "🇮🇳"),
        "Indonesia": (code: "+62", flag: "🇮🇩"),
        "Iran": (code: "+98", flag: "🇮🇷"),
        "Iraq": (code: "+964", flag: "🇮🇶"),
        "Ireland": (code: "+353", flag: "🇮🇪"),
        "Isle of Man": (code: "+44-1624", flag: "🇮🇲"),
        "Israel": (code: "+972", flag: "🇮🇱"),
        "Italy": (code: "+39", flag: "🇮🇹"),
        "Ivory Coast": (code: "+225", flag: "🇨🇮"),
        "Jamaica": (code: "+1-876", flag: "🇯🇲"),
        "Japan": (code: "+81", flag: "🇯🇵"),
        "Jersey": (code: "+44-1534", flag: "🇯🇪"),
        "Jordan": (code: "+962", flag: "🇯🇴"),
        "Kazakhstan": (code: "+7", flag: "🇰🇿"),
        "Kenya": (code: "+254", flag: "🇰🇪"),
        "Kiribati": (code: "+686", flag: "🇰🇮"),
        "Kosovo": (code: "+383", flag: "🇽🇰"),
        "Kuwait": (code: "+965", flag: "🇰🇼"),
        "Kyrgyzstan": (code: "+996", flag: "🇰🇬"),
        "Laos": (code: "+856", flag: "🇱🇦"),
        "Latvia": (code: "+371", flag: "🇱🇻"),
        "Lebanon": (code: "+961", flag: "🇱🇧"),
        "Lesotho": (code: "+266", flag: "🇱🇸"),
        "Liberia": (code: "+231", flag: "🇱🇷"),
        "Libya": (code: "+218", flag: "🇱🇾"),
        "Liechtenstein": (code: "+423", flag: "🇱🇮"),
        "Lithuania": (code: "+370", flag: "🇱🇹"),
        "Luxembourg": (code: "+352", flag: "🇱🇺"),
        "Macau": (code: "+853", flag: "🇲🇴"),
        "Madagascar": (code: "+261", flag: "🇲🇬"),
        "Malawi": (code: "+265", flag: "🇲🇼"),
        "Malaysia": (code: "+60", flag: "🇲🇾"),
        "Maldives": (code: "+960", flag: "🇲🇻"),
        "Mali": (code: "+223", flag: "🇲🇱"),
        "Malta": (code: "+356", flag: "🇲🇹"),
        "Marshall Islands": (code: "+692", flag: "🇲🇭"),
        "Mauritania": (code: "+222", flag: "🇲🇷"),
        "Mauritius": (code: "+230", flag: "🇲🇺"),
        "Mexico": (code: "+52", flag: "🇲🇽"),
        "Micronesia": (code: "+691", flag: "🇫🇲"),
        "Moldova": (code: "+373", flag: "🇲🇩"),
        "Monaco": (code: "+377", flag: "🇲🇨"),
        "Mongolia": (code: "+976", flag: "🇲🇳"),
        "Montenegro": (code: "+382", flag: "🇲🇪"),
        "Montserrat": (code: "+1-664", flag: "🇲🇸"),
        "Morocco": (code: "+212", flag: "🇲🇦"),
        "Mozambique": (code: "+258", flag: "🇲🇿"),
        "Myanmar": (code: "+95", flag: "🇲🇲"),
        "Namibia": (code: "+264", flag: "🇳🇦"),
        "Nauru": (code: "+674", flag: "🇳🇷"),
        "Nepal": (code: "+977", flag: "🇳🇵"),
        "Netherlands": (code: "+31", flag: "🇳🇱"),
        "New Zealand": (code: "+64", flag: "🇳🇿"),
        "Nicaragua": (code: "+505", flag: "🇳🇮"),
        "Niger": (code: "+227", flag: "🇳🇪"),
        "Nigeria": (code: "+234", flag: "🇳🇬"),
        "Niue": (code: "+683", flag: "🇳🇺"),
        "North Korea": (code: "+850", flag: "🇰🇵"),
        "North Macedonia": (code: "+389", flag: "🇲🇰"),
        "Norway": (code: "+47", flag: "🇳🇴"),
        "Oman": (code: "+968", flag: "🇴🇲"),
        "Pakistan": (code: "+92", flag: "🇵🇰"),
        "Palau": (code: "+680", flag: "🇵🇼"),
        "Palestine": (code: "+970", flag: "🇵🇸"),
        "Panama": (code: "+507", flag: "🇵🇦"),
        "Papua New Guinea": (code: "+675", flag: "🇵🇬"),
        "Paraguay": (code: "+595", flag: "🇵🇾"),
        "Peru": (code: "+51", flag: "🇵🇪"),
        "Philippines": (code: "+63", flag: "🇵🇭"),
        "Pitcairn Islands": (code: "+64", flag: "🇵🇳"),
        "Poland": (code: "+48", flag: "🇵🇱"),
        "Portugal": (code: "+351", flag: "🇵🇹"),
        "Puerto Rico": (code: "+1-787", flag: "🇵🇷"),
        "Qatar": (code: "+974", flag: "🇶🇦"),
        "Republic of the Congo": (code: "+242", flag: "🇨🇬"),
        "Romania": (code: "+40", flag: "🇷🇴"),
        "Russia": (code: "+7", flag: "🇷🇺"),
        "Rwanda": (code: "+250", flag: "🇷🇼"),
        "Saint Barthélemy": (code: "+590", flag: "🇧🇱"),
        "Saint Helena": (code: "+290", flag: "🇸🇭"),
        "Saint Kitts and Nevis": (code: "+1-869", flag: "🇰🇳"),
        "Saint Lucia": (code: "+1-758", flag: "🇱🇨"),
        "Saint Martin": (code: "+590", flag: "🇲🇫"),
        "Saint Pierre and Miquelon": (code: "+508", flag: "🇵🇲"),
        "Saint Vincent and the Grenadines": (code: "+1-784", flag: "🇻🇨"),
        "Samoa": (code: "+685", flag: "🇼🇸"),
        "San Marino": (code: "+378", flag: "🇸🇲"),
        "São Tomé and Príncipe": (code: "+239", flag: "🇸🇹"),
        "Saudi Arabia": (code: "+966", flag: "🇸🇦"),
        "Senegal": (code: "+221", flag: "🇸🇳"),
        "Serbia": (code: "+381", flag: "🇷🇸"),
        "Seychelles": (code: "+248", flag: "🇸🇨"),
        "Sierra Leone": (code: "+232", flag: "🇸🇱"),
        "Singapore": (code: "+65", flag: "🇸🇬"),
        "Sint Maarten": (code: "+1-721", flag: "🇸🇽"),
        "Slovakia": (code: "+421", flag: "🇸🇰"),
        "Slovenia": (code: "+386", flag: "🇸🇮"),
        "Solomon Islands": (code: "+677", flag: "🇸🇧"),
        "Somalia": (code: "+252", flag: "🇸🇴"),
        "South Africa": (code: "+27", flag: "🇿🇦"),
        "South Korea": (code: "+82", flag: "🇰🇷"),
        "South Sudan": (code: "+211", flag: "🇸🇸"),
        "Spain": (code: "+34", flag: "🇪🇸"),
        "Sri Lanka": (code: "+94", flag: "🇱🇰"),
        "Sudan": (code: "+249", flag: "🇸🇩"),
        "Suriname": (code: "+597", flag: "🇸🇷"),
        "Svalbard and Jan Mayen": (code: "+47", flag: "🇸🇯"),
        "Sweden": (code: "+46", flag: "🇸🇪"),
        "Switzerland": (code: "+41", flag: "🇨🇭"),
        "Syria": (code: "+963", flag: "🇸🇾"),
        "Taiwan": (code: "+886", flag: "🇹🇼"),
        "Tajikistan": (code: "+992", flag: "🇹🇯"),
        "Tanzania": (code: "+255", flag: "🇹🇿"),
        "Thailand": (code: "+66", flag: "🇹🇭"),
        "Timor-Leste": (code: "+670", flag: "🇹🇱"),
        "Togo": (code: "+228", flag: "🇹🇬"),
        "Tokelau": (code: "+690", flag: "🇹🇰"),
        "Tonga": (code: "+676", flag: "🇹🇴"),
        "Trinidad and Tobago": (code: "+1-868", flag: "🇹🇹"),
        "Tunisia": (code: "+216", flag: "🇹🇳"),
        "Turkey": (code: "+90", flag: "🇹🇷"),
        "Turkmenistan": (code: "+993", flag: "🇹🇲"),
        "Turks and Caicos Islands": (code: "+1-649", flag: "🇹🇨"),
        "Tuvalu": (code: "+688", flag: "🇹🇻"),
        "Uganda": (code: "+256", flag: "🇺🇬"),
        "Ukraine": (code: "+380", flag: "🇺🇦"),
        "United Arab Emirates": (code: "+971", flag: "🇦🇪"),
        "United Kingdom": (code: "+44", flag: "🇬🇧"),
        "United States": (code: "+1", flag: "🇺🇸"),
        "Uruguay": (code: "+598", flag: "🇺🇾"),
        "Uzbekistan": (code: "+998", flag: "🇺🇿"),
        "Vanuatu": (code: "+678", flag: "🇻🇺"),
        "Vatican City": (code: "+379", flag: "🇻🇦"),
        "Venezuela": (code: "+58", flag: "🇻🇪"),
        "Vietnam": (code: "+84", flag: "🇻🇳"),
        "Wallis and Futuna": (code: "+681", flag: "🇼🇫"),
        "Western Sahara": (code: "+212", flag: "🇪🇭"),
        "Yemen": (code: "+967", flag: "🇾🇪"),
        "Zambia": (code: "+260", flag: "🇿🇲"),
        "Zimbabwe": (code: "+263", flag: "🇿🇼")
    ]
    
    @Published var selectedCountry: CountryModel? = nil
    
    func getCountryList() -> [CountryModel] {
        let list = countryDictionary.map { dict in
            CountryModel(name: dict.key.capitalized, code: dict.value.code, flag: dict.value.flag)
        }
        return list
    }
    
    func searchCountry(name: String) -> [CountryModel] {
        if countryDictionary[name] == nil {
            let listOfCountries = countryDictionary.first { (key: String, value: (code: String, flag: String)) in
                key.lowercased().contains(name.lowercased())
            }.map { dict in
                [CountryModel(name: dict.key.capitalized, code: dict.value.code, flag: dict.value.flag)]
            }
            return listOfCountries ?? []
        }
        return [CountryModel(name: name.capitalized, code: countryDictionary[name]!.code, flag: countryDictionary[name]!.flag)]
    }
}
