# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameTicTacToe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameTicTacToe
pod 'SwiftLint'
  target 'GameTicTacToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameTicTacToeUITests' do
    # Pods for testing
  end

end
