# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

def common_pods
  pod 'SwiftLint'
end

target 'CleanArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for CleanArchitecture
  common_pods

  target 'CleanArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanArchitectureUITests' do
    # Pods for testing
  end

end
