# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tidoy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tidoy
  pod 'SwiftLint'
  target 'TidoyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TidoyUITests' do
    # Pods for testing
  end

end
